const Blog = require('../../models/Blog')

const blogs = [
    {
        user_id: 1,
        title: "Javascript 101",
        contents: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec tincidunt praesent semper feugiat. Arcu risus quis varius quam. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. At in tellus integer feugiat. Nec ultrices dui sapien eget. Integer enim neque volutpat ac. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Nec dui nunc mattis enim ut tellus elementum sagittis vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam.\n" +
            "\n" +
            "Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Cras ornare arcu dui vivamus. Dictum at tempor commodo ullamcorper a lacus vestibulum. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Faucibus in ornare quam viverra. Lectus nulla at volutpat diam ut venenatis. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Massa tempor nec feugiat nisl pretium fusce id velit ut. Cursus turpis massa tincidunt dui ut ornare lectus sit. Sit amet est placerat in egestas erat. Egestas dui id ornare arcu odio ut sem. Venenatis cras sed felis eget velit aliquet.\n" +
            "\n" +
            "Ut sem nulla pharetra diam. Vivamus arcu felis bibendum ut tristique et egestas. Sit amet nisl suscipit adipiscing. Volutpat lacus laoreet non curabitur gravida arcu. Aliquam purus sit amet luctus. Sed velit dignissim sodales ut eu sem integer vitae justo. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Mauris rhoncus aenean vel elit. Quis commodo odio aenean sed adipiscing diam donec adipiscing tristique. Ut diam quam nulla porttitor massa id neque. Mi ipsum faucibus vitae aliquet nec ullamcorper. Varius vel pharetra vel turpis nunc eget. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Mi quis hendrerit dolor magna eget est lorem.",
        created_at: "2022-01-01 11:03:00"
    },
    {
        user_id: 2,
        title: "Learning MySQL",
        contents: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Id consectetur purus ut faucibus. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. In egestas erat imperdiet sed euismod nisi porta. Commodo viverra maecenas accumsan lacus vel. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Nisi quis eleifend quam adipiscing vitae proin sagittis. Duis at consectetur lorem donec massa sapien faucibus et. Semper feugiat nibh sed pulvinar proin. Sed elementum tempus egestas sed sed. Faucibus vitae aliquet nec ullamcorper. Eget lorem dolor sed viverra ipsum nunc aliquet. Elementum facilisis leo vel fringilla est ullamcorper. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Tempor nec feugiat nisl pretium. Odio pellentesque diam volutpat commodo sed egestas. Duis at consectetur lorem donec massa sapien faucibus et molestie. Egestas sed tempus urna et.\n" +
            "\n" +
            "Vulputate eu scelerisque felis imperdiet. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem. Malesuada fames ac turpis egestas maecenas pharetra convallis. Nisi est sit amet facilisis magna etiam tempor orci eu. Cras ornare arcu dui vivamus arcu felis bibendum. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Sed blandit libero volutpat sed cras. Sit amet cursus sit amet dictum sit amet justo donec. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Nec ullamcorper sit amet risus nullam eget. Lacus sed viverra tellus in hac. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Magna etiam tempor orci eu. Risus in hendrerit gravida rutrum quisque non. Vitae congue eu consequat ac felis. Tincidunt arcu non sodales neque.\n" +
            "\n" +
            "Non blandit massa enim nec dui nunc mattis enim ut. Quisque non tellus orci ac auctor augue mauris. Elit ut aliquam purus sit amet luctus venenatis. Eget nunc scelerisque viverra mauris in aliquam. Interdum posuere lorem ipsum dolor. Tellus molestie nunc non blandit. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Ut venenatis tellus in metus vulputate eu scelerisque felis. Lobortis feugiat vivamus at augue eget arcu dictum varius. Lectus quam id leo in. Nisl suscipit adipiscing bibendum est ultricies integer quis. Lectus quam id leo in vitae turpis. Curabitur vitae nunc sed velit dignissim sodales. Quam vulputate dignissim suspendisse in est. Et netus et malesuada fames ac turpis egestas integer eget. Vivamus arcu felis bibendum ut tristique et egestas quis. Sapien faucibus et molestie ac feugiat sed.",
        created_at: "2022-02-21 12:18:00"
    },
    {
        user_id: 3,
        title: "Creating Web App with Express",
        contents: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Pellentesque nec nam aliquam sem et tortor consequat id porta. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Tellus molestie nunc non blandit. Magna eget est lorem ipsum dolor. In mollis nunc sed id semper risus in hendrerit. Tortor at auctor urna nunc id. Risus pretium quam vulputate dignissim suspendisse.\n" +
            "\n" +
            "Sed risus ultricies tristique nulla aliquet. Viverra orci sagittis eu volutpat. Lectus sit amet est placerat in egestas. Bibendum at varius vel pharetra vel turpis nunc eget. Nullam eget felis eget nunc. Fermentum odio eu feugiat pretium nibh ipsum consequat. Et ligula ullamcorper malesuada proin. Nisl vel pretium lectus quam id leo in. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Diam quis enim lobortis scelerisque fermentum dui. Urna neque viverra justo nec. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Dolor purus non enim praesent elementum facilisis. Nec tincidunt praesent semper feugiat nibh sed. Vestibulum lorem sed risus ultricies tristique nulla aliquet. In aliquam sem fringilla ut. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Vulputate dignissim suspendisse in est ante in nibh.\n" +
            "\n" +
            "Varius vel pharetra vel turpis nunc eget lorem. Malesuada fames ac turpis egestas sed tempus. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Euismod elementum nisi quis eleifend quam adipiscing. Congue eu consequat ac felis. Malesuada proin libero nunc consequat. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Ut tristique et egestas quis ipsum suspendisse ultrices. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Diam in arcu cursus euismod. Felis imperdiet proin fermentum leo. Sed odio morbi quis commodo. Duis at consectetur lorem donec massa.",
        created_at: "2022-03-01 08:01:00"
    },
    {
        user_id: 4,
        title: "Mastering Regular Expressions",
        contents: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed turpis tincidunt id aliquet risus feugiat. Arcu cursus vitae congue mauris. Enim nunc faucibus a pellentesque sit amet porttitor. Velit ut tortor pretium viverra. Malesuada proin libero nunc consequat interdum varius. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Vehicula ipsum a arcu cursus vitae congue.\n" +
            "\n" +
            "Quis viverra nibh cras pulvinar. Tempus egestas sed sed risus pretium. Turpis massa sed elementum tempus egestas sed sed. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Non consectetur a erat nam at lectus. Ac turpis egestas maecenas pharetra convallis posuere morbi leo. Eu turpis egestas pretium aenean pharetra magna ac placerat. Habitasse platea dictumst quisque sagittis purus. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Nibh ipsum consequat nisl vel. Blandit massa enim nec dui. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium.\n" +
            "\n" +
            "Mauris augue neque gravida in fermentum et sollicitudin. Condimentum vitae sapien pellentesque habitant morbi. Fusce id velit ut tortor. Urna neque viverra justo nec. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Volutpat lacus laoreet non curabitur gravida arcu ac. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Semper quis lectus nulla at volutpat diam ut. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Suscipit tellus mauris a diam maecenas. Urna condimentum mattis pellentesque id nibh. Nibh tellus molestie nunc non blandit massa enim. Feugiat scelerisque varius morbi enim.",
        created_at: "2022-06-14 18:59:00"
    },
]

const seedCategories = () => Blog.bulkCreate(blogs)

module.exports = seedCategories